ros2_control:
  ros__parameters:
    update_rate: 30
    use_sim_time: true

controller_manager:
  ros__parameters:
    update_rate: 30
    use_sim_time: true

    diff_cont:
      type: diff_drive_controller/DiffDriveController
      publish_rate: 50.0

    joint_broad:
      type: joint_state_broadcaster/JointStateBroadcaster

diff_cont:
  ros__parameters:
    base_frame_id: base_link
    left_wheel_names: ["base_to_left_wheel"]
    right_wheel_names: ["base_to_right_wheel"]
    wheel_separation: 0.575
    wheel_radius: 0.155
    use_stamped_vel: false
    
